mimosa: mimosa.c rsa.c aes.c bignum.c
	//gcc -g -O0 -o mimosa mimosa.c rsa.c aes.c bignum.c
	gcc -g -O0 -o decrypt_service decrypt_service.c rsa.c aes.c bignum.c

clean:
	//rm -f *.o mimosa
	rm -f *.o decrypt_service
